version: "3.4"
services:
    nopcommerce_database:
        image: "postgres:latest"
        container_name: nopcommerce_postgres_server
        restart: "always"
        environment:
          POSTGRES_USER: "nopCommerce_db_user"
          POSTGRES_PASSWORD: "nopCommerce_db_password"
        volumes:
          - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
volumes:
  postgres_data: